### ISSUE TITLE
Thank you for your excellent work

### ISSUE THREAD

**Issue by joexsyd** [XuRobotics/SLIDE_SLAM#3]
Thank you for your excellent work. When do you plan to open-source it? I'm eager to learn about the technical details.

**Comment by XuRobotics** [comment]
Thank you for your interest. We are currently working on additional exciting functionalities (e.g. support for open-vocabulary object detectors) and refactoring our code stack to make it easy to build and use. We plan to start releasing our core code base within the next 1-2 months, with more functionalities to follow.
