### ISSUE TITLE
LiDAR demo bags 

### ISSUE THREAD

**Issue by joexsyd** [XuRobotics/SLIDE_SLAM#7]
Thank you for your excellent work. However, I didn't see the LiDAR demo bags in the outdoor folder of the raw sensor data. Have they not been uploaded yet?

**Comment by XuRobotics** [comment]
Thanks for catching this! I did not realize that the upload was interrupted. I just re-uploaded it. You can find it here: https://drive.google.com/drive/folders/1O9MnN7HuVifYdxr01L_CAuOfSKppmTtK
